Repository godotengine/godot-website, pull requests merged in 2020-11, with the labels that each got.

#198 Fix 404 errors due to extraneous Blog component usage declaration
  themes/godotengine/partials/head.htm
Labels: bug, topic:backend

#200 Display a caption for the header image in blog posts
  themes/godotengine/layouts/article.htm
Labels: enhancement, topic:theme

#202 Add a link to third-party tutorials on the Community page
  themes/godotengine/pages/community.htm
Labels: enhancement, topic:content

#203 Link to Blender ESCN exporter in the Download page
  themes/godotengine/layouts/download.htm
Labels: enhancement, topic:content

#206 Point license tutorial link to new directory
  themes/godotengine/pages/license.htm
Labels: bug, topic:content
