Repository godotengine/godot-website, pull requests merged in 2021-05, with the labels that each got.

#332 Add `security.txt` file for standardized security issue reporting
  .well-known/security.txt
Labels: enhancement, topic:content

#333 Update Download page for 3.3.1-stable
  themes/godotengine/layouts/download.htm
  themes/godotengine/layouts/home.htm
Labels: enhancement

#336 Move latest version identifier and release date to an included file
  themes/godotengine/layouts/download.htm
  themes/godotengine/layouts/home.htm
  themes/godotengine/pages/download/linux.htm
  themes/godotengine/pages/download/osx.htm
  themes/godotengine/pages/download/server.htm
  themes/godotengine/pages/download/windows.htm
  themes/godotengine/partials/version.htm
Labels: enhancement, topic:backend

#335 Fix GodotCon banner overlaying Patreon banner
  lighthouserc.js
  themes/godotengine/assets/css/main.css
  themes/godotengine/partials/header.htm
Labels: bug, topic:theme

#334 Update user-groups.htm
  themes/godotengine/pages/user-groups.htm
Labels: enhancement, topic:content

#338 Fix GodotCon banner appearing in front of the navigation bar
  themes/godotengine/partials/header.htm
Labels: bug, topic:theme
