Repository godotengine/godot-website, pull requests merged in 2021-09, with the labels that each got.

#364 Fix tabs having extra padding in mobile view
  themes/godotengine/assets/css/main.css
Labels: bug, topic:theme

#366 Fix typo of pronunciation in Press Kit
  themes/godotengine/pages/press.htm
Labels: bug

#367 Update Pixelorama's showcase page to 0.9
  themes/godotengine/assets/showcase/pixelorama.png
  themes/godotengine/pages/showcase/pixelorama.htm
Labels: enhancement, topic:content

#365 Update security contact for new email address
  .well-known/security.txt
  themes/godotengine/pages/contact.htm
Labels: enhancement, topic:content

#362 Fix the navigation bar dropdown being drawn behind the homepage message
  themes/godotengine/layouts/home.htm
Labels: bug, topic:theme
