Repository godotengine/godot-website, pull requests merged in 2021-08, with the labels that each got.

#350 Optimize press kit images using `oxipng -o6 --strip --zopfli`
  themes/godotengine/assets/home/sponsors/litslink.png
  themes/godotengine/assets/press/icon_color.png
  themes/godotengine/assets/press/icon_color_outline.png
  themes/godotengine/assets/press/icon_monochrome_dark.png
  themes/godotengine/assets/press/icon_monochrome_light.png
  themes/godotengine/assets/press/logo_large_color_dark.png
  themes/godotengine/assets/press/logo_large_color_light.png
  themes/godotengine/assets/press/logo_large_monochrome_dark.png
  themes/godotengine/assets/press/logo_large_monochrome_light.png
  themes/godotengine/assets/press/logo_small_color_dark.png
  themes/godotengine/assets/press/logo_small_color_light.png
  themes/godotengine/assets/press/logo_small_monochrome_dark.png
  themes/godotengine/assets/press/logo_small_monochrome_light.png
  themes/godotengine/assets/press/logo_vertical_color_dark.png
  themes/godotengine/assets/press/logo_vertical_color_light.png
  themes/godotengine/assets/press/logo_vertical_monochrome_dark.png
  themes/godotengine/assets/press/logo_vertical_monochrome_light.png
Labels: enhancement, topic:content

#347 Remove cacheroute plugin, breaks live instance
  .github/workflows/ci.yml
  plugins/serenitynow/cacheroute/Plugin.php
  plugins/serenitynow/cacheroute/README.md
  plugins/serenitynow/cacheroute/classes/RouteCacheMiddleware.php
  plugins/serenitynow/cacheroute/controllers/CacheRoutes.php
  plugins/serenitynow/cacheroute/controllers/cacheroutes/_list_toolbar.htm
  plugins/serenitynow/cacheroute/controllers/cacheroutes/_reorder_toolbar.htm
  plugins/serenitynow/cacheroute/controllers/cacheroutes/config_form.yaml
  plugins/serenitynow/cacheroute/controllers/cacheroutes/config_list.yaml
  plugins/serenitynow/cacheroute/controllers/cacheroutes/config_reorder.yaml
  plugins/serenitynow/cacheroute/controllers/cacheroutes/create.htm
  plugins/serenitynow/cacheroute/controllers/cacheroutes/index.htm
  plugins/serenitynow/cacheroute/controllers/cacheroutes/preview.htm
  plugins/serenitynow/cacheroute/controllers/cacheroutes/reorder.htm
  plugins/serenitynow/cacheroute/controllers/cacheroutes/update.htm
  plugins/serenitynow/cacheroute/lang/en/lang.php
  plugins/serenitynow/cacheroute/models/CacheRoute.php
  plugins/serenitynow/cacheroute/models/cacheroute/columns.yaml
  plugins/serenitynow/cacheroute/models/cacheroute/fields.yaml
  plugins/serenitynow/cacheroute/plugin.yaml
  plugins/serenitynow/cacheroute/updates/builder_table_create_serenitynow_cacheroute_routes.php
  plugins/serenitynow/cacheroute/updates/builder_table_update_serenitynow_cacheroute_routes.php
  plugins/serenitynow/cacheroute/updates/version.yaml
Labels: bug

#358 Fix navbar dropdown appearing on mobile when it shouldn't
  themes/godotengine/assets/css/main.css
Labels: bug, topic:theme
