Repository godotengine/godot-website, pull requests merged in 2021-04, with the labels that each got.

#316 Add a banner for GodotCon July 2021
  themes/godotengine/partials/header.htm
Labels: enhancement, topic:content

#317 Add instructions for installing Godot using MacPorts
  themes/godotengine/pages/download/osx.htm
Labels: enhancement, topic:content

#320 Hide the GodotCon banner on mobile
  themes/godotengine/partials/header.htm
Labels: bug, topic:theme

#322 Update link to website discussion channel in the README
  README.md
Labels: enhancement

#323 Press kit: Change previews background color to match website theme
  themes/godotengine/pages/press.htm
Labels: enhancement, topic:content

#325 Update Home and Download pages for Godot 3.3's release
  themes/godotengine/layouts/download.htm
  themes/godotengine/layouts/home.htm
  themes/godotengine/pages/download/linux.htm
  themes/godotengine/pages/download/osx.htm
  themes/godotengine/pages/download/server.htm
  themes/godotengine/pages/download/windows.htm
Labels: enhancement, topic:content

#327 Add a margin between non-Mono and Mono download links
  themes/godotengine/layouts/download.htm
Labels: enhancement, topic:theme
