Repository godotengine/godot-website, pull requests merged in 2021-12, with the labels that each got.

#341 Update Godot Mono prerequisites: .NET SDK
  themes/godotengine/layouts/download.htm
Labels: enhancement, topic:content

#379 Fix open source redirect on the homepage
  themes/godotengine/layouts/home.htm
Labels: bug, topic:content

#380 Fix off-center "Learn more" button on the homepage
  themes/godotengine/assets/css/main.css
Labels: bug, topic:theme
