Repository godotengine/godot-website, pull requests merged in 2022-07, with the labels that each got.

#400 Add Philippines user group to the community map
  themes/godotengine/pages/user-groups.htm
Labels: enhancement, topic:content

#404 Improve contribution and docker instructions
  .gitignore
  DEVELOPMENT_SETUP.md
  README.md
Labels: enhancement

#405 Make docker setup work consistently cross-platform
  .gitattributes
  docker/php/init/docker-entrypoint.sh
  docker/php/init/init.sh
Labels: bug

#402 Rework top and bottom navigation, reorganize the downloads page
  themes/godotengine/assets/css/main.css
  themes/godotengine/layouts/download.htm
  themes/godotengine/layouts/features.htm
  themes/godotengine/layouts/more-standalone.htm
  themes/godotengine/layouts/more.htm
  themes/godotengine/pages/donate.htm
  themes/godotengine/pages/features.htm
  themes/godotengine/pages/press.htm
  themes/godotengine/pages/showcase.htm
  themes/godotengine/pages/teams.htm
  themes/godotengine/pages/user-groups.htm
  themes/godotengine/partials/footer.htm
  themes/godotengine/partials/head.htm
  themes/godotengine/partials/header.htm
Labels: enhancement

#411 Cross-link the Teams page from the Governance page
  themes/godotengine/pages/governance.htm
Labels: enhancement

#413 Move the About link in the header to reduce significance
  themes/godotengine/partials/header.htm
Labels: enhancement

#412 Improve formatting of shell instructions and extra links for Downloads
  themes/godotengine/assets/css/main.css
  themes/godotengine/layouts/download.htm
  themes/godotengine/pages/download/osx.htm
  themes/godotengine/pages/download/windows.htm
Labels: enhancement

#408 Fix sitemap group title color in the footer
  themes/godotengine/assets/css/main.css
Labels: bug

#417 Teams: Add Production team
  themes/godotengine/pages/teams.htm
Labels: enhancement, topic:content
