Repository godotengine/godot-website, pull requests merged in 2022-08, with the labels that each got.

#416 Update designs for text-heavy pages
  themes/godotengine/assets/css/main.css
  themes/godotengine/pages/code-of-conduct.htm
  themes/godotengine/pages/contact.htm
  themes/godotengine/pages/governance.htm
  themes/godotengine/pages/license.htm
  themes/godotengine/pages/privacy-policy.htm
  themes/godotengine/pages/teams.htm
Labels: enhancement, topic:theme

#415 Update XR support section on Features page
  themes/godotengine/pages/features.htm
Labels: enhancement, topic:content

#420 Fix a typo in name on Teams page
  themes/godotengine/pages/teams.htm
Labels: bug, topic:content

#421 Add Android editor download page
  themes/godotengine/assets/css/main.css
  themes/godotengine/layouts/download.htm
  themes/godotengine/pages/download.htm
  themes/godotengine/pages/download/android.htm
  themes/godotengine/pages/features.htm
  themes/godotengine/partials/head.htm
Labels: enhancement, topic:content

#424 Governance: Add Clay John to list of PLC members
  themes/godotengine/pages/governance.htm
Labels: enhancement, topic:content

#426 Fix text overflow on Teams page on mobile
  themes/godotengine/assets/css/main.css
Labels: bug, topic:content

#403 Add a simple education page
  themes/godotengine/pages/education.htm
  themes/godotengine/partials/footer.htm
Labels: enhancement, topic:content

#425 Add android logo to cross-platform asset
  themes/godotengine/assets/home/features/cross-platform.svg
  themes/godotengine/assets/home/features/cross_platform.webp
  themes/godotengine/layouts/home.htm
Labels: enhancement, topic:content

#428 Add JPEG library to the docker setup
  docker/php/Dockerfile
Labels: topic:docker

#427 Make the sponsors block more attractive looking
  themes/godotengine/assets/css/main.css
  themes/godotengine/layouts/home.htm
Labels: enhancement, topic:theme

#429 Separate the text and the image of the home page's highlight section
  themes/godotengine/assets/css/main.css
  themes/godotengine/layouts/home.htm
Labels: enhancement, topic:theme

#430 Fix City Game Studio trailer URL on showcase page
  themes/godotengine/pages/showcase/city-game-studio.htm
Labels: bug, topic:content
