Repository godotengine/godot-website, pull requests merged in 2023-02, with the labels that each got.

#549 Donate page
  _config.yml
  _data/sponsors.yml
  assets/css/transparent-nav.css
  assets/images/donate/hero.png
  pages/donate.html
  pages/home.html
Labels: enhancement, topic:content

#550 blog: Add "Dev snapshot: Godot 4.0 beta 17"
  collections/_article/dev-snapshot-godot-4-0-beta-17.md
  storage/blog/covers/dev-snapshot-godot-4-0-beta-17.jpg
Labels: topic:blog

#552 blog: Add "Release candidate: Godot 4.0 RC 1"
  collections/_article/release-candidate-godot-4-0-rc-1.md
  storage/blog/covers/release-candidate-godot-4-0-rc-1.jpg
Labels: topic:blog

#553 Overhaul the downloads page
  .gitignore
  Gemfile.lock
  _config.development.yml
  _layouts/default.html
  _layouts/download.html
  assets/css/main.css
  assets/download/download-background.jpg
  assets/icons/linux-server.svg
  build-and-watch.sh
  collections/_download/android.md
  collections/_download/linux.md
  collections/_download/macos.md
  collections/_download/server.md
  collections/_download/windows.md
Labels: enhancement, topic:theme, topic:content

#554 Improve page metadata across the board
  _layouts/blog.html
  collections/_download/android.md
  collections/_download/linux.md
  collections/_download/macos.md
  collections/_download/server.md
  collections/_download/windows.md
  pages/code-of-conduct.html
  pages/contact.html
  pages/download.html
  pages/events.html
  pages/features.html
  pages/governance.html
  pages/license.html
  pages/privacy-policy.html
  pages/showcase.html
  pages/teams.html
Labels: topic:theme, topic:content

#558 blog: Add "Release candidate: Godot 4.0 RC 2"
  collections/_article/release-candidate-godot-4-0-rc-2.md
  storage/blog/covers/release-candidate-godot-4-0-rc-2.jpg
Labels: topic:blog

#557 Add tiers to the donation page
  assets/images/donate/bronze.png
  assets/images/donate/diamond.png
  assets/images/donate/gold.png
  assets/images/donate/platinum.png
  assets/images/donate/silver.png
  assets/images/donate/titanium.png
  pages/donate.html
Labels: enhancement, topic:content

#563 Add a CI workflow for PRs
  .github/workflows/build-pr.yml
Labels: enhancement, topic:backend

#555 Make the main scrollbar follow user's color preference
  assets/css/main.css
Labels: bug, topic:theme

#564 Update Godot website license and update Godot license on the website
  LICENSE.txt
  pages/license.html
Labels: bug, enhancement, topic:content

#566 Use sponsor data on the home page
  pages/home.html
Labels: enhancement, topic:content

#565 Add a call for donations to after starting a download
  _layouts/default.html
  _layouts/download.html
  assets/cross.svg
  assets/css/main.css
  pages/donate.html
Labels: enhancement, topic:content

#568 blog: Add "Release candidate: Godot 4.0 RC 3"
  collections/_article/release-candidate-godot-4-0-rc-3.md
  storage/blog/covers/release-candidate-godot-4-0-rc-3.jpg
Labels: topic:blog

#562 blog: Add "Multiplayer in Godot 4.0: Scene Replication"
  collections/_article/multiplayer-in-godot-4-0-scene-replication.md
  storage/blog/covers/multiplayer-in-godot-4-0-scene-replication.jpg
  storage/blog/multiplayer-in-godot-4-0-scene-replication/client_server_side_by_side.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/debug-multiple-instances.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/level_spawner.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/multiplayer-level.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/multiplayer-synchronizer.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/multiplayer-ui.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/player_input_sync.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/player_server_sync.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/player_spawner.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/project.zip
Labels: topic:blog

#570 blog: Add "Release candidate: Godot 4.0 RC 4"
  collections/_article/release-candidate-godot-4-0-rc-4.md
  storage/blog/covers/release-candidate-godot-4-0-rc-4.jpg
Labels: topic:blog

#574 blog: Add "Release candidate: Godot 4.0 RC 5"
  collections/_article/release-candidate-godot-4-0-rc-5.md
  storage/blog/covers/release-candidate-godot-4-0-rc-5.jpg
Labels: topic:blog

#573 Promote Play Store version of the Android editor
  _layouts/download.html
  collections/_download/android.md
Labels: enhancement, topic:content

#569 Overhaul the Features page
  _includes/footer.html
  _includes/showreel-shelf.html
  _layouts/default.html
  assets/arrow-flip.svg
  assets/css/main.css
  assets/features/2dgames.jpg
  assets/features/3dgames.jpg
  assets/features/animate.jpg
  assets/features/editor-frame.png
  assets/features/games_2d.jpg
  assets/features/games_3d.jpg
  assets/features/script.jpg
  assets/features/xrsupport.jpg
  pages/donate.html
  pages/features.html
  pages/showcase.html
Labels: enhancement, topic:content

#575 blog: Add "What's new in C# for Godot 4.0"
  collections/_article/whats-new-in-csharp-for-godot-4-0.md
  storage/blog/covers/whats-new-in-csharp-for-godot-4-0.jpg
Labels: topic:blog

#576 blog: Add client prediction to "Multiplayer in Godot 4.0: Scene Replication"
  collections/_article/multiplayer-in-godot-4-0-scene-replication.md
  storage/blog/multiplayer-in-godot-4-0-scene-replication/player_server_sync.png
  storage/blog/multiplayer-in-godot-4-0-scene-replication/project.zip
Labels: enhancement, topic:blog

#578 blog: Add "Release candidate: Godot 4.0 RC 6"
  collections/_article/release-candidate-godot-4-0-rc-6.md
  storage/blog/covers/release-candidate-godot-4-0-rc-6.jpg
Labels: topic:blog
