Repository godotengine/godot-website, pull requests merged in 2023-04, with the labels that each got.

#613 Add Godot User Group Berlin data
  _data/communities.yml
Labels: topic:content

#614 blog: Add "Maintenance Release: Godot 4.0.2"
  _data/versions.yml
  collections/_article/maintenance-release-godot-4-0-2.md
  storage/blog/covers/maintenance-release-godot-4-0-2.jpg
Labels: topic:content, topic:blog

#605 Remove incorrect "have" from 4.0.1 release blog
  collections/_article/maintenance-release-godot-4-0-1.md
Labels: bug, topic:blog

#616 Add Madness/Endless to showcase page
  _layouts/showcase-item.html
  assets/showcase/lumen-showcase.jpg
  assets/showcase/lumencraft-2.jpg
  assets/showcase/madness-endless-1.jpg
  assets/showcase/madness-endless-2.jpg
  assets/showcase/madness-endless-header.png
  collections/_showcase/lumencraft.md
  collections/_showcase/madness-endless.md
Labels: topic:content

#617 Fix a couple of typos in gdc-2023 blog
  collections/_article/gdc-2023-retrospective.md
Labels: bug, topic:blog

#618 Add Direct3D 12 shaders technical discussion blog post
  collections/_article/d3d12-adventures-in-shaderland.md
  storage/blog/covers/d3d12-adventures-in-shaderland.jpg
  storage/blog/d3d12/isa-a.png
  storage/blog/d3d12/isa-b.png
  storage/blog/d3d12/scs-in-dxil.jpg
Labels: topic:blog

#620 Add blog post on rendering priorities for Godot 4.1
  collections/_article/rendering-priorities-4-1.md
  storage/blog/covers/rendering-priorities-4-1.png
Labels: topic:blog

#624 Reduce vertical space in Blog
  _layouts/blog.html
Labels: enhancement, topic:theme

#627 Improve readability of the blog's search bar
  assets/css/main.css
  pages/404.html
Labels: bug, topic:theme

#628 Rework community events using data collections
  _config.yml
  _includes/events-list.html
  _includes/events-year.html
  _layouts/event.html
  _layouts/showcase-item.html
  collections/_event/fosdem-2017.md
  collections/_event/fosdem-2018.md
  collections/_event/fosdem-2019.md
  collections/_event/fosdem-2020.md
  collections/_event/gdcbooth-2023.md
  collections/_event/gdcmeetup-2019.md
  collections/_event/gdcmeetup-2023.md
  collections/_event/godotcon-2017.md
  collections/_event/godotcon-2018.md
  collections/_event/godotcon-2019.md
  collections/_event/godotcon-2020.md
  collections/_event/godotmeeting-2022.md
  collections/_event/godotmeetup-2023.md
  collections/_event/godotsprint-2019.md
  collections/_event/godotsprint-2020.md
  collections/_event/godotsprint-2022.md
  collections/_event/godotsprint-2023.md
  collections/_event/meetthenodes-2017.md
  collections/_showcase/primal-light.md
  collections/templates/article.md
  collections/templates/event.md
  collections/templates/showcase.md
  pages/events.html
Labels: bug, enhancement, topic:content

#631 Update GDScript team
  pages/teams.html
Labels: enhancement, topic:content
