Repository godotengine/godot-website, pull requests merged in 2023-01, with the labels that each got.

#502 Add Heroic Labs as a sponsor
  themes/godotengine/assets/home/sponsors/heroiclabs.png
  themes/godotengine/layouts/home.htm
Labels: topic:content

#503 Update name and pronouns for HP
  themes/godotengine/pages/code-of-conduct.htm
  themes/godotengine/pages/contact.htm
  themes/godotengine/pages/governance.htm
  themes/godotengine/pages/teams.htm
Labels: enhancement, topic:content

#505 Make build scripts executable
  .gitignore
  build-and-serve.sh
  build.sh
Labels: bug, topic:backend

#506 Update name and pronouns for HP, including in past blog posts (static version)
  _data/authors.yml
  collections/_article/dev-snapshot-godot-2-1-5-rc-2.md
  collections/_article/dev-snapshot-godot-3-0-1-rc1.md
  collections/_article/dev-snapshot-godot-3-0-3-rc-1.md
  collections/_article/dev-snapshot-godot-3-0-3-rc-2.md
  collections/_article/dev-snapshot-godot-3-0-3-rc-3.md
  collections/_article/dev-snapshot-godot-3-1-alpha-5.md
  collections/_article/dev-snapshot-godot-3-1-beta-10.md
  collections/_article/dev-snapshot-godot-3-1-beta-11.md
  collections/_article/dev-snapshot-godot-3-1-beta-6.md
  collections/_article/dev-snapshot-godot-3-1-beta-7.md
  collections/_article/dev-snapshot-godot-3-1-beta-8.md
  collections/_article/dev-snapshot-godot-3-1-beta-9.md
  collections/_article/dev-snapshot-godot-3-2-alpha-2.md
  collections/_article/dev-snapshot-godot-3-2-beta-4.md
  collections/_article/fbx-importer-rewritten-for-godot-3-2-4.md
  collections/_article/fixing-godot-games-published-google-play.md
  collections/_article/george-marques-will-be-working-full-time-project.md
  collections/_article/godot-3-0-released.md
  collections/_article/godot-3-1-released.md
  collections/_article/godot-3-3-has-arrived.md
  collections/_article/godot-apk-fixer-tool.md
  collections/_article/godot-google-summer-code-2018.md
  collections/_article/godot-project-management-101.md
  collections/_article/gsoc-2018-progress-report-1.md
  collections/_article/gsoc-2019-progress-report-1-part-2.md
  collections/_article/gsoc-2019-progress-report-2.md
  collections/_article/gsoc-2019-progress-report-3.md
  collections/_article/maintenance-release-godot-3-0-1.md
  collections/_article/maintenance-release-godot-3-0-3.md
  collections/_article/maintenance-release-godot-3-0-4.md
  collections/_article/maintenance-release-godot-3-0-5.md
  collections/_article/maintenance-release-godot-3-0-6.md
  collections/_article/maintenance-release-godot-3-1-1.md
  collections/_article/maintenance-release-godot-302.md
  collections/_article/release-candidate-godot-3-1-1-rc-1.md
  collections/_article/release-candidate-godot-3-1-2-rc-1.md
  collections/_article/release-candidate-godot-3-1-rc-1.md
  collections/_article/release-candidate-godot-3-1-rc-2.md
  collections/_article/release-candidate-godot-3-1-rc-3.md
  collections/_article/schedule-godotcon-2019-brussels.md
  collections/_article/why-we-broke-your-pr.md
  pages/code-of-conduct.html
  pages/contact.html
  pages/governance.html
  pages/teams.html
Labels: enhancement, topic:content

#507 Add heroic lab to home page
  assets/home/sponsors/heroiclabs.png
  pages/home.html
Labels: topic:content

#508 Add new articles on static site (up to date as of 13/01/2023)
  _data/authors.yml
  assets/images/authors/maxhilbrunner.png
  collections/_article/dev-snapshot-godot-4-0-beta-11.md
  collections/_article/dev-snapshot-godot-4-0-beta-12.md
  collections/_article/godot-4-0-docs-sprint.md
  collections/_article/release-candidate-godot-3-5-2-rc-2.md
  storage/app/uploads/public/63b/d87/318/63bd873180f42194998123.jpg
  storage/app/uploads/public/63b/eba/ed6/63bebaed69c6c649257378.png
  storage/app/uploads/public/63c/053/77e/63c05377eaa1e774008524.jpg
  storage/app/uploads/public/63c/17e/368/63c17e3689796351687911.jpg
Labels: topic:content

#509 Enable `.editorconfig` to enforce formatting, make sure build-and-serve works
  .editorconfig
  Gemfile
  Gemfile.lock
  README.md
  build-and-serve.sh
Labels: bug, enhancement, topic:backend, topic:content

#511 Add alt text to showreel images
  pages/showcase.html
Labels: enhancement, topic:theme

#512 Add "en" to the value on the default html tag
  _layouts/default.html
Labels: topic:theme

#514 Remove empty files from articles
  collections/_article/georgemjesus@gmail.com.md
  collections/_article/godot-aaa-whats-missing.md
  collections/_article/godot-gets-mobile-vulkan-renderer.md
  collections/_article/sdfgi-under-hood.md
  collections/_article/some-graphs-about-godots-use-last-global-game-jam.md
Labels: bug, topic:blog

#517 Add missing fbx-import
  pages/fbx-import.html
Labels: bug, topic:content

#518 Fix RSS feed format
  pages/rss.xml
Labels: bug, topic:content

#523 Add site.baseurl variable to fix OG image previews
  _config.yml
  _layouts/default.html
  pages/rss.xml
Labels: bug, topic:content

#526 Add untracked production files to .gitignore
  .github/workflows/build-website.yml
  .gitignore
Labels: enhancement

#524 blog: Add "Dev snapshot: Godot 4.0 beta 13"
  collections/_article/dev-snapshot-godot-4-0-beta-13.md
  storage/blog/covers/dev-snapshot-godot-4-0-beta-13.jpg
Labels: topic:blog

#533 Improve What's Missing AAA article
  collections/_article/whats-missing-in-godot-for-aaa.md
Labels: bug, enhancement, topic:blog

#536 blog: Add "Dev snapshot: Godot 4.0 beta 14"
  collections/_article/dev-snapshot-godot-4-0-beta-14.md
  storage/blog/covers/dev-snapshot-godot-4-0-beta-14.jpg
Labels: topic:blog

#539 Fix broken link in "More programming languages in Godot" blog post
  collections/_article/godot-getting-more-languages.md
Labels: bug, topic:blog

#541 Add kamaeru page
  _layouts/showcase-item.html
  assets/showcase/kamaeru-1.png
  assets/showcase/kamaeru-2.png
  assets/showcase/kamaeru-header.png
  collections/_showcase/kamaeru.md
Labels: topic:content

#542 blog: Add "Dev snapshot: Godot 4.0 beta 15"
  collections/_article/dev-snapshot-godot-4-0-beta-15.md
  storage/blog/covers/dev-snapshot-godot-4-0-beta-15.jpg
Labels: topic:blog

#537 Blog: add note for articles that might be outdated
  _includes/outdated_article_notice.html
  _layouts/article.html
  _plugins/outdated_article_threshold.rb
  assets/css/main.css
Labels: enhancement, topic:backend, topic:blog

#543 blog: Add "Dev snapshot: Godot 4.0 beta 16"
  collections/_article/dev-snapshot-godot-4-0-beta-16.md
  storage/blog/covers/dev-snapshot-godot-4-0-beta-16.jpg
Labels: topic:blog

#544 blog: Fix incorrect mention of SSIL as SSGI
  collections/_article/whats-missing-in-godot-for-aaa.md
Labels: bug, topic:blog

#546 Add more fields to RSS items
  pages/rss.xml
Labels: enhancement

#545 blog: add Godot XR Progress report Jan 2023
  collections/_article/godot-xr-progress-update-jan-2023.md
  storage/blog/covers/godot-xr-progress-update-jan-2023.jpg
Labels: topic:blog
