Repository godotengine/godot-website, pull requests merged in 2023-03, with the labels that each got.

#580 Add Lumencraft and A Most Extraordinary Gnome
  assets/showcase/gnome-1.jpg
  assets/showcase/gnome-2.jpg
  assets/showcase/gnome-3.jpg
  assets/showcase/gnome-header.jpg
  assets/showcase/lumencraft-1.jpg
  assets/showcase/lumencraft-2.jpg
  assets/showcase/lumencraft-3.jpg
  assets/showcase/lumencraft-header.jpg
  collections/_showcase/a-most-extraordinary-gnome.md
  collections/_showcase/lumencraft.md
Labels: topic:content

#577 blog: Add "Godot 4.0 sets sail: All aboard for new horizons"
  _data/authors.yml
  assets/images/authors/everyone.jpg
  collections/_article/godot-4-0-sets-sail.md
  storage/blog/covers/godot-4-0-sets-sail.webp
  storage/blog/godot-4-0-sets-sail/02-3d-gi-sdfgi.webp
  storage/blog/godot-4-0-sets-sail/02-3d-gi-voxelgi.webp
  storage/blog/godot-4-0-sets-sail/02-3d-occlusion-culling.webp
  storage/blog/godot-4-0-sets-sail/02-3d-outdoor-with-editor.webp
  storage/blog/godot-4-0-sets-sail/02-3d-shadows.mp4
  storage/blog/godot-4-0-sets-sail/03-2d-clip-content.png
  storage/blog/godot-4-0-sets-sail/03-2d-directional-lights.png
  storage/blog/godot-4-0-sets-sail/03-2d-tilemap-editor.mp4
  storage/blog/godot-4-0-sets-sail/03-2d-tilemap-level-at-runtime.mp4
  storage/blog/godot-4-0-sets-sail/04-vfx-decals.mp4
  storage/blog/godot-4-0-sets-sail/04-vfx-improved-visual-shaders.png
  storage/blog/godot-4-0-sets-sail/04-vfx-particle-trails.mp4
  storage/blog/godot-4-0-sets-sail/04-vfx-sky-shaders.webp
  storage/blog/godot-4-0-sets-sail/04-vfx-volumetric-fog.webp
  storage/blog/godot-4-0-sets-sail/05-scripting-multiple-errors.png
  storage/blog/godot-4-0-sets-sail/05-scripting-new-syntax.png
  storage/blog/godot-4-0-sets-sail/06-physics-ball-pool.mp4
  storage/blog/godot-4-0-sets-sail/06-physics-better-character-body.png
  storage/blog/godot-4-0-sets-sail/06-physics-kicking-ball.mp4
  storage/blog/godot-4-0-sets-sail/08-editor-new-ui-editing-options.png
  storage/blog/godot-4-0-sets-sail/08-ui-multiple-windows-protongraph.webp
  storage/blog/godot-4-0-sets-sail/08-ui-text-in-different-languages.mp4
  storage/blog/godot-4-0-sets-sail/08-ui-theme-editor.png
  storage/blog/godot-4-0-sets-sail/10-editor-color-picker.webp
  storage/blog/godot-4-0-sets-sail/10-editor-floating-dock.png
  storage/blog/godot-4-0-sets-sail/10-editor-import-window.png
  storage/blog/godot-4-0-sets-sail/10-editor-multiple-cursors.mp4
  storage/blog/godot-4-0-sets-sail/11-navigation-links.webp
  storage/blog/godot-4-0-sets-sail/13-networking-rpcs.png
  storage/blog/godot-4-0-sets-sail/15-animation-sophia-retargeting.png
  storage/blog/godot-4-0-sets-sail/15-tween-code.png
  storage/blog/godot-4-0-sets-sail/15-tween-demo.mp4
  storage/blog/godot-4-0-sets-sail/16-godot-on-android.webp
Labels: topic:blog

#587 Improve styling of the features page (and some buttons)
  assets/css/main.css
  pages/features.html
  pages/home.html
Labels: bug, topic:theme

#589 Fix case of macOS in download layout
  _layouts/download-3.html
  _layouts/download.html
Labels: bug, topic:theme

#556 Anchor links to headings
  _layouts/article.html
  assets/js/anchor-link.js
Labels: enhancement, topic:theme

#592 GDC blog post and event
  assets/showcase/until-then-header.jpg
  collections/_article/gdc-2023-godot-games.md
  collections/_showcase/until-then.md
  pages/events.html
  storage/app/media/events/gdc-2023.jpg
  storage/app/media/events/gdc-banner.jpg
  storage/blog/covers/gdc2023.jpg
  storage/blog/gdc/gawr-gura.jpg
Labels: topic:content

#593 Improve styling and layout of articles
  _includes/footer.html
  _layouts/article.html
  _layouts/blog.html
  _layouts/default.html
  assets/css/anchor-link.css
  assets/css/main.css
  assets/icons/link.svg
  assets/js/anchor-link.js
  collections/_article/godot-4-0-sets-sail.md
Labels: bug, enhancement, topic:theme

#596 blog: Add "Maintenance release: Godot 3.5.2"
  README.md
  _data/versions.yml
  collections/_article/maintenance-release-godot-3-5-2.md
  storage/blog/covers/maintenance-release-godot-3-5-2.jpg
Labels: topic:blog

#594 Features.html: Fixes up minor grammar issues
  pages/features.html
Labels: bug, topic:content

#598 Use GitHub as the main download source everywhere
  _layouts/download-3.html
  pages/maintenance.html
Labels: enhancement, topic:content

#599 Add Epic Games Store link to the downloads page
  _layouts/download-3.html
  _layouts/download.html
  assets/css/download.css
  assets/download/epic_logo.svg
  assets/download/godot_logo.svg
  assets/download/steam_logo.svg
Labels: enhancement, topic:content

#600 blog: Add "Release candidate: Godot 4.0.1 RC 1"
  _config.yml
  collections/_article/gdc-2023-godot-games.md
  collections/_article/release-candidate-godot-4-0-1-rc-1.md
  storage/blog/covers/release-candidate-godot-4-0-1-rc-1.jpg
Labels: topic:blog

#602 blog: Add "Release Candidate: Godot 4.0.1 RC 2"
  collections/_article/release-candidate-godot-4-0-1-rc-1.md
  collections/_article/release-candidate-godot-4-0-1-rc-2.md
  storage/blog/covers/release-candidate-godot-4-0-1-rc-2.jpg
Labels: topic:blog

#601 Adding EGS press release
  collections/_article/godot-arrives-in-the-epic-games-store.md
  storage/blog/covers/godot-epic-games-store.jpg
Labels: topic:blog

#604 blog: Add "Maintenance Release: Godot 4.0.1"
  _data/versions.yml
  collections/_article/godot-arrives-in-the-epic-games-store.md
  collections/_article/maintenance-release-godot-4-0-1.md
  collections/_article/release-candidate-godot-4-0-1-rc-2.md
  storage/blog/covers/maintenance-release-godot-4-0-1.jpg
Labels: enhancement, topic:content, topic:blog

#611 blog: Add "Release Candidate: Godot 4.0.2 RC 1"
  collections/_article/release-candidate-godot-4-0-2-rc-1.md
  storage/blog/covers/release-candidate-godot-4-0-2-rc-1.jpg
Labels: topic:blog
