Repository godotengine/godot-website, pull requests merged in 2024-09, with the labels that each got.

#925 Add showreel submissions post
  _layouts/default.html
  collections/_article/submissions-open-godot-2024-showreel.md
  storage/blog/covers/godot-showreel-2024.webp
Labels: topic:content

#932 Nav, hero and buttons design update
  _includes/header.html
  assets/css/article-cards.css
  assets/css/main.scss
  assets/css/releases/4.3.scss
  assets/css/transparent-nav.css
  assets/css/transparent-nav.scss
Labels: enhancement, topic:theme

#934 Fixes incorrect release date for Godot 3.6 on Download page
  _data/versions.yml
Labels: bug

#936 Download: Add Horizon OS APK and Horizon Store app, minor refactoring
  _data/download_configs.yml
  _data/download_platforms.yml
  _layouts/download.html
Labels: enhancement, topic:content

#933 Add a blog post about rendering priorities as of September 2024
  collections/_article/rendering-priorities-september-2024.md
  storage/blog/covers/rendering-priorities-september-2024.webp
Labels: topic:blog

#938 Add announcement for Godot SDK Integrations organization
  collections/_article/godot-sdk-integrations.md
  storage/blog/covers/godot-sdk-integrations.webp
Labels: topic:blog
