Repository godotengine/godot-website, pull requests merged in 2024-06, with the labels that each got.

#862 Fix C# link in 4.3.beta1 blog post
  collections/_article/dev-snapshot-godot-4-3-beta-1.md
Labels: bug, topic:blog

#863 Fix `minify` generation of `./_site/`
  _plugins/minify-assets.rb
Labels: bug, topic:releases

#866 Drop 'Blender ESCN exporter' from download pages
  _layouts/download-3.html
  _layouts/download.html
  assets/css/download.css
Labels: bug, topic:content

#864 Fix relative path issue with `minify`
  _plugins/minify-assets.rb
Labels: bug, topic:content

#868 Upload site as artifact
  .github/workflows/build-pr.yml
Labels: enhancement, topic:backend

#867 Link to Linux desktop integration instructions (#802)
  _layouts/download-3.html
  _layouts/download.html
Labels: enhancement, topic:content

#872 Release blog post for 4.3-beta2
  _data/versions.yml
  collections/_article/dev-snapshot-godot-4-3-beta-1.md
  collections/_article/dev-snapshot-godot-4-3-beta-2.md
  storage/blog/covers/dev-snapshot-godot-4-3-beta-2.webp
Labels: topic:blog

#873 Add article about gamescom latam 2024
  collections/_article/gamescom-latam-2024.md
  storage/blog/covers/gamescom-latam-2024.webp
  storage/blog/gamescom-latam-2024/booth-2023.webp
  storage/blog/gamescom-latam-2024/booth-render-2024.webp
Labels: topic:blog

#876 Add poll blogpost
  collections/_article/godot-community-poll-2024.md
  storage/blog/covers/community-poll-2024.webp
Labels: topic:content
