Repository godotengine/godot-website, pull requests merged in 2024-08, with the labels that each got.

#888 Add blog post for 4.3 RC 2
  _data/versions.yml
  collections/_article/release-candidate-godot-4-3-rc-1.md
  collections/_article/release-candidate-godot-4-3-rc-2.md
  storage/blog/covers/release-candidate-godot-4-3-rc-2.webp
Labels: topic:blog

#852 Add ufbx importer article
  _data/authors.yml
  assets/images/authors/lyuma.webp
  collections/_article/introducing-the-improved-ufbx-importer-in-godot-4-3.md
  storage/blog/covers/progress-report-new-ufbx-importer.webp
Labels: topic:blog

#890 Fix issues URL in ufbx article
  collections/_article/introducing-the-improved-ufbx-importer-in-godot-4-3.md
Labels: topic:blog

#891 Fix url link for RC1 redirecting to RC2(itself)
  collections/_article/release-candidate-godot-4-3-rc-2.md
Labels: bug, topic:blog

#885 Update download page to add Windows arm64 binaries
  _data/download_configs.yml
  _data/download_platforms.yml
Labels: topic:releases

#894 Add blog post for 4.3 RC 3
  _data/versions.yml
  collections/_article/release-candidate-godot-4-3-rc-3.md
  storage/blog/covers/release-candidate-godot-4-3-rc-3.webp
Labels: topic:blog

#854 Add Skeleton modifier design article
  collections/_article/design-of-the-skeleton-modifier-3d.md
  storage/blog/covers/design-of-the-skeleton-modifier-3d.webp
  storage/blog/design-of-the-skeleton-modifier-3d/add_skeleton_modifier.webp
  storage/blog/design-of-the-skeleton-modifier-3d/bones_enum.webp
  storage/blog/design-of-the-skeleton-modifier-3d/custom_modifier.webm
  storage/blog/design-of-the-skeleton-modifier-3d/different_process_orders.webp
  storage/blog/design-of-the-skeleton-modifier-3d/mod.webp
  storage/blog/design-of-the-skeleton-modifier-3d/modified_pose.webp
  storage/blog/design-of-the-skeleton-modifier-3d/modifier_callback_mode_process.webp
  storage/blog/design-of-the-skeleton-modifier-3d/register_custom_modifier.webp
  storage/blog/design-of-the-skeleton-modifier-3d/skeleton-modifier-3d-demo-project.zip
  storage/blog/design-of-the-skeleton-modifier-3d/skeleton_modifier_process.webp
Labels: topic:blog

#896 Fix link to demo project ZIP in skeleton modifier article
  collections/_article/design-of-the-skeleton-modifier-3d.md
Labels: bug, topic:blog

#897 Bypass sass to force background-position of logo
  pages/releases/4.3.html
Labels: topic:releases

#899 Add links to the ARM binaries to the main download page.
  collections/_download/linux.md
  collections/_download/windows.md
Labels: enhancement, topic:content

#900 Make `/releases` redirect to `/releases/4.3/`
  pages/releases/index.html
Labels: topic:releases

#902 Fix missing image in 4.3 download page
  _data/versions.yml
Labels: topic:content, topic:releases

#907 New footer design
  _includes/footer.html
  _layouts/download-archive.html
  _sass/_footer.scss
  assets/css/main.scss
  assets/css/release.scss
  assets/footer/facebook_logo.svg
  assets/footer/feed_logo.svg
  assets/footer/github_logo.svg
  assets/footer/mastodon_logo.svg
  assets/footer/reddit_logo.svg
  assets/footer/twitter_logo.svg
  pages/community/community.html
  pages/download/archive.html
  pages/download/preview.html
  pages/features.html
  pages/showcase/showcase.scss
Labels: enhancement, topic:theme

#629 Create next and previous buttons below the articles
  _layouts/article.html
Labels: enhancement, topic:theme

#911 Add blog post for 4.4 dev1
  _data/versions.yml
  collections/_article/dev-snapshot-godot-4-4-dev-1.md
  storage/blog/covers/dev-snapshot-godot-4-4-dev-1.webp
  storage/blog/dev-snapshot-godot-4-4-dev-1/bicubic-compare.webp
  storage/blog/dev-snapshot-godot-4-4-dev-1/physics-interpolation.mp4
Labels: topic:blog

#918 Fix Godot 4.4-dev1 download page preview
  _data/versions.yml
Labels: bug

#917 Add new submissions page
  pages/showcase/index.html
  pages/showcase/submissions.html
Labels: topic:content
