Repository godotengine/godot-website, pull requests merged in 2024-02, with the labels that each got.

#793 Highlight recent post dates on homepage and article metadata
  _includes/footer.html
  _layouts/article.html
  assets/css/main.css
  pages/home.html
Labels: enhancement, topic:theme

#794 Fix recent post highlight date threshold
  _includes/footer.html
Labels: bug, topic:theme

#795 Release Godot 4.3 dev 3 and publish release notes
  _data/versions.yml
  collections/_article/dev-snapshot-godot-4-3-dev-3.md
  storage/blog/covers/dev-snapshot-godot-4-3-dev-3.webp
Labels: enhancement, topic:blog

#800 Add GDC 2024 post
  collections/_article/godot-at-gdc-2024.md
  storage/blog/gdc/2024/gdc-thumbnail.webp
Labels: topic:blog

#804 Fix features page carousel image position
  pages/features.html
Labels: bug, topic:theme

#801 Directed acyclic graph for rendering device article.
  _data/authors.yml
  assets/images/authors/dario.webp
  collections/_article/rendering-acyclic-graph.md
  storage/blog/acyclic-graph/barriers.webp
  storage/blog/acyclic-graph/benchmark-particles.png
  storage/blog/acyclic-graph/benchmark-projects.png
  storage/blog/acyclic-graph/command-graph-levels.webp
  storage/blog/acyclic-graph/command-graph.webp
  storage/blog/acyclic-graph/complex-scene.webp
  storage/blog/acyclic-graph/dependency-tracking-animated.webp
  storage/blog/acyclic-graph/draw-compute-lists.webp
  storage/blog/acyclic-graph/msaa-resolve-manual.webp
  storage/blog/acyclic-graph/msaa-resolve-solution.webp
  storage/blog/acyclic-graph/multi-queue.webp
  storage/blog/acyclic-graph/particle-error-fix.webp
  storage/blog/acyclic-graph/particle-error.webp
  storage/blog/acyclic-graph/resource-tracking.webp
  storage/blog/acyclic-graph/texture-slices.webp
  storage/blog/covers/gpu-sync-progress-report.webp
Labels: topic:blog

#799 Asset minification
  .github/workflows/build-pr.yml
  .github/workflows/build-website.yml
  README.md
  _includes/header.html
  _plugins/minify-assets.rb
Labels: enhancement, topic:backend

#812 Update teams page
  pages/teams.html
Labels: enhancement, topic:content

#815 Release Godot 4.3 dev 4 and publish release notes
  _data/versions.yml
  collections/_article/dev-snapshot-godot-4-3-dev-4.md
  storage/blog/covers/dev-snapshot-godot-4-3-dev-4.webp
Labels: topic:releases
