Repository godotengine/godot-website, pull requests merged in 2024-10, with the labels that each got.

#943 Add blog post for 4.4 dev 3
  _data/versions.yml
  collections/_article/dev-snapshot-godot-4-4-dev-3.md
  storage/blog/covers/dev-snapshot-godot-4-4-dev-3.webp
  storage/blog/dev-snapshot-godot-4-4-dev-3/auto-start.webp
  storage/blog/dev-snapshot-godot-4-4-dev-3/editor_tool_button.webp
  storage/blog/dev-snapshot-godot-4-4-dev-3/export_tool_button.gif
  storage/blog/dev-snapshot-godot-4-4-dev-3/markers.mp4
  storage/blog/dev-snapshot-godot-4-4-dev-3/markers2.mp4
  storage/blog/dev-snapshot-godot-4-4-dev-3/repl.webp
  storage/blog/dev-snapshot-godot-4-4-dev-3/vertex_shading.webp
Labels: topic:blog

#945 Add a "what's new" button to home page
  pages/home.html
Labels: enhancement, topic:theme

#931 Add fallback and error to minify
  _plugins/minify-assets.rb
Labels: enhancement, topic:backend
