Repository godotengine/godot-website, pull requests merged in 2024-05, with the labels that each got.

#828 Fix grammar in features.html
  pages/features.html
Labels: bug, topic:content

#736 Add User Group listing for godot.community
  _data/communities.yml
Labels: enhancement, topic:content

#840 Make hero shorter and update call to actions
  _includes/header.html
  assets/css/main.css
  pages/home.html
Labels: enhancement, topic:theme

#845 Remove showcase submission form
  pages/showcase.html
Labels: bug

#844 Godot 3.6 beta 5 blog post
  _data/versions.yml
  collections/_article/dev-snapshot-godot-3-6-beta-5.md
  storage/blog/covers/dev-snapshot-godot-3-6-beta-5.webp
  storage/blog/godot-3.6/lod_node_scene.webp
  storage/blog/godot-3.6/merge_group_house.webp
  storage/blog/godot-3.6/view_mesh_stats.webp
Labels: enhancement, topic:blog

#846 Add way to customize host and port for `build-and-serve.sh`
  build-and-serve.sh
Labels: enhancement, topic:backend

#843 Add Web Export in 4.3 progress report article
  _data/authors.yml
  assets/css/main.css
  assets/images/authors/adamscott.webp
  collections/_article/progress-report-web-export-in-4-3.md
  storage/blog/covers/progress-report-web-export-in-4-3.webp
  storage/blog/progress-report-web-export-in-4-3/default-playback-type.webp
  storage/blog/progress-report-web-export-in-4-3/ensure-cross-origin-isolation-headers.webp
  storage/blog/progress-report-web-export-in-4-3/loading-screen.gif
  storage/blog/progress-report-web-export-in-4-3/playback-type.webp
  storage/blog/progress-report-web-export-in-4-3/register-stream.webp
  storage/blog/progress-report-web-export-in-4-3/sample-library.webp
  storage/blog/progress-report-web-export-in-4-3/thread-support-export-option.webp
  storage/blog/progress-report-web-export-in-4-3/web-audio-schema.webp
Labels: topic:content

#847 Fix date of the newly merged "Web Export in 4.3"
  collections/_article/progress-report-web-export-in-4-3.md
Labels: bug, topic:blog

#857 Avoid redirects in internal links by appending trailing slash
  _includes/articles/download_card.html
  _includes/download/download-section.html
  _includes/footer.html
  _includes/header.html
  _layouts/blog.html
  _layouts/download-3.html
  _layouts/download.html
  _layouts/more.html
  _layouts/showcase-item.html
  collections/_event/fosdem-2017.md
  pages/404.html
  pages/community/community.html
  pages/contact.html
  pages/download.html
  pages/education.html
  pages/features.html
  pages/governance.html
  pages/home.html
  pages/license.html
  pages/privacy-policy.html
  pages/showcase.html
  pages/teams.html
Labels: enhancement, topic:content

#856 Add blog post and cover photo for 4.3 beta 1
  _data/versions.yml
  collections/_article/dev-snapshot-godot-4-3-beta-1.md
  storage/blog/covers/dev-snapshot-godot-4-3-beta-1.webp
Labels: topic:blog

#858 Simplify the version.json output
  versions.json
Labels: enhancement, topic:releases

#859 Add missing interactive music section in 4.3.beta1 blog post
  collections/_article/dev-snapshot-godot-4-3-beta-1.md
Labels: bug, enhancement, topic:blog
