Repository godotengine/godot-website, pull requests merged in 2024-03, with the labels that each got.

#816 Fix link to UFBX PR in 4.3 dev4 blog post
  collections/_article/dev-snapshot-godot-4-3-dev-4.md
Labels: bug, topic:releases

#817 Add GDC 2024 blog post about the event, games, and the schedule
  collections/_article/gdc-2024-godot-games.md
  storage/blog/gdc/2024/endoparasitic.webp
  storage/blog/gdc/2024/gdc2.webp
  storage/blog/gdc/2024/hallsoftorment.webp
  storage/blog/gdc/2024/kohlrabistarship.webp
  storage/blog/gdc/2024/nonu.webp
  storage/blog/gdc/2024/springdash.webp
  storage/blog/gdc/2024/stuntxpress.webp
  storage/blog/gdc/2024/warside.webp
  storage/blog/gdc/2024/windowkill.webp
Labels: topic:blog

#820 Add Godot links to Community tab
  pages/community/community.html
Labels: enhancement, topic:content

#821 Add post for RC2s of 4.2.2 and 4.1.4
  _data/versions.yml
  collections/_article/release-candidate-godot-4-1-4-and-4-2-2-rc-1.md
  collections/_article/release-candidate-godot-4-1-4-and-4-2-2-rc-2.md
  storage/blog/covers/release-candidate-godot-4-1-4-and-4-2-2-rc-2.webp
Labels: topic:releases

#822 4.3 dev5 release post
  _data/versions.yml
  collections/_article/dev-snapshot-godot-4-3-dev-5.md
  storage/blog/covers/dev-snapshot-godot-4-3-dev-5.webp
Labels: topic:releases
