Repository godotengine/godot-website, pull requests merged in 2025-08, with the labels that each got.

#1136 Update communities.yml
  _data/communities.yml
Labels: enhancement, topic:content

#1137 Add gamescom community meetup to event list
  _includes/events/events-list.html
  assets/css/events.css
  collections/_event/gamescom-2025.md
  storage/blog/gamescom-cologne-2025/gamescom-cover.webp
Labels: topic:content

#1140 Showreel submission post 2025
  collections/_article/submissions-open-godot-2025-showreel.md
Labels: topic:blog

#1150 Add 4.5-beta7 blog post
  _data/versions.yml
  collections/_article/dev-snapshot-godot-4-5-beta-6.md
  collections/_article/dev-snapshot-godot-4-5-beta-7.md
  storage/blog/covers/dev-snapshot-godot-4-5-beta-7.webp
Labels: topic:releases, topic:blog

#1153 Fix Buckshot Roulette website URL in showcase
  collections/_showcase/buckshot-roulette.md
Labels: bug, topic:content
